services:
  # Web service
  - type: web
    name: appraisalai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8001
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: appraisalai-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: NEBIUS_API_KEY
        sync: false
      - key: NEBIUS_ENDPOINT
        value: https://api.studio.nebius.com/v1/chat/completions
      - key: MODEL_NAME
        value: meta-llama/Meta-Llama-3.1-70B-Instruct

databases:
  - name: appraisalai-db
    databaseName: appraisalai
    user: appraisalai
    plan: free
