services:
  # Web service
  - type: web
    name: appraisalai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py --api-only
    envVars:
      - key: PORT
        value: 8002
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        fromDatabase:
          name: appraisalai-db
          property: secret_key
      - key: NEBIUS_API_KEY
        sync: false
      - key: NEBIUS_ENDPOINT
        value: https://api.studio.nebius.com/v1/chat/completions
      - key: MODEL_NAME
        value: meta-llama/Meta-Llama-3.1-70B-Instruct

databases:
  - name: appraisalai-db
    databaseName: appraisalai
    user: appraisalai
